# -*- coding: utf-8 -*-
"""variaciones_salarios_2138449.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M03dfWXj0DdNrBzwVoRdEeBCOTbyq5FE
"""

#CODIGO RODRIGO 2138449, GRAFICAR SALARIOS DE 5 EMPLEADOS PARA VER VARIACIONES


import matplotlib.pyplot as plt

save_name = []
save_salary = []

for i in range(5):
  nombre_empleado = input("Dame tu nombre: ")
  salario_empleado = float(input("Dame tu salario: "))
  save_name.append(nombre_empleado)
  save_salary.append(salario_empleado)

print(save_name)
print(save_salary)

#Datos_a_usar_opcional = {
# 'rodrigo' : 15000,
# 'saul' :  14000,
# 'romeo' : 23000,
# 'josue' : 18000,
# 'Emmanuel' :  16000}

#Gráfica_Mat-plotlib
plt.bar(save_name, save_salary)
plt.title("Relación empleado y salarios")
plt.xlabel("Nombre_empleado")
plt.ylabel("Salarios_empleados")

#guardamos y mostramos
plt.savefig("grafica_salarios.png")
plt.show()

